// Free Agents data - replace with real data when available
// r = rank, n = name, p = position, age = age, tm = current team abbr, aav = projected AAV in millions, stats = key stat line, tags = projected landing spots
const FREE_AGENTS = [
// ── Quarterbacks ──
{r:1,n:"Lamar Jackson",p:"QB",age:29,tm:"BAL",aav:52.0,stats:"4,172 YDS · 34 TD · 8 INT · 821 RUSH",tags:["BAL","ATL","NYG"]},
{r:8,n:"Sam Darnold",p:"QB",age:28,tm:"MIN",aav:40.0,stats:"4,153 YDS · 35 TD · 12 INT",tags:["MIN","NYG","LV"]},
{r:25,n:"Justin Fields",p:"QB",age:27,tm:"PIT",aav:22.0,stats:"2,492 YDS · 16 TD · 7 INT · 467 RUSH",tags:["PIT","LV","NYG"]},
{r:58,n:"Russell Wilson",p:"QB",age:37,tm:"PIT",aav:15.0,stats:"2,058 YDS · 13 TD · 5 INT",tags:["NYG","LV","TEN"]},
{r:95,n:"Aaron Rodgers",p:"QB",age:42,tm:"NYJ",aav:10.0,stats:"3,623 YDS · 24 TD · 11 INT",tags:["RETIRE","MIN","IND"]},
{r:110,n:"Jameis Winston",p:"QB",age:32,tm:"CLE",aav:8.0,stats:"2,012 YDS · 13 TD · 8 INT",tags:["CLE","LV","CAR"]},
{r:130,n:"Marcus Mariota",p:"QB",age:32,tm:"WAS",aav:4.0,stats:"Backup · 312 YDS · 2 TD",tags:["WAS","NYG","NE"]},
// ── Running Backs ──
{r:15,n:"Saquon Barkley",p:"RB",age:29,tm:"PHI",aav:14.0,stats:"2,005 YDS · 13 TD · 33 REC",tags:["PHI","HOU","BUF"]},
{r:30,n:"Josh Jacobs",p:"RB",age:28,tm:"GB",aav:10.0,stats:"1,329 YDS · 15 TD · 37 REC",tags:["GB","DET","DAL"]},
{r:55,n:"Aaron Jones",p:"RB",age:31,tm:"MIN",aav:7.0,stats:"1,138 YDS · 5 TD · 41 REC",tags:["MIN","SEA","CHI"]},
{r:75,n:"Tony Pollard",p:"RB",age:28,tm:"TEN",aav:7.5,stats:"1,017 YDS · 7 TD · 29 REC",tags:["TEN","MIA","ATL"]},
{r:105,n:"Najee Harris",p:"RB",age:28,tm:"PIT",aav:5.0,stats:"1,043 YDS · 6 TD · 22 REC",tags:["PIT","JAX","LV"]},
{r:125,n:"J.K. Dobbins",p:"RB",age:27,tm:"LAC",aav:5.5,stats:"766 YDS · 8 TD · 17 REC",tags:["LAC","DEN","NYG"]},
{r:140,n:"Raheem Mostert",p:"RB",age:33,tm:"MIA",aav:3.0,stats:"614 YDS · 4 TD · 12 REC",tags:["MIA","RETIRE","DAL"]},
{r:155,n:"Alexander Mattison",p:"RB",age:27,tm:"LV",aav:2.5,stats:"496 YDS · 3 TD · 18 REC",tags:["LV","DEN","SEA"]},
// ── Wide Receivers ──
{r:2,n:"Tee Higgins",p:"WR",age:27,tm:"CIN",aav:28.0,stats:"911 YDS · 7 TD · 73 REC",tags:["CIN","NYG","WAS"]},
{r:5,n:"Chris Godwin",p:"WR",age:30,tm:"TB",aav:22.0,stats:"840 YDS · 5 TD · 68 REC",tags:["TB","DAL","BUF"]},
{r:12,n:"Diontae Johnson",p:"WR",age:29,tm:"BAL",aav:16.0,stats:"645 YDS · 3 TD · 55 REC",tags:["BAL","CHI","JAX"]},
{r:22,n:"Darnell Mooney",p:"WR",age:28,tm:"ATL",aav:15.0,stats:"1,015 YDS · 6 TD · 74 REC",tags:["ATL","CHI","NE"]},
{r:40,n:"Michael Pittman Jr.",p:"WR",age:28,tm:"IND",aav:14.0,stats:"780 YDS · 4 TD · 62 REC",tags:["IND","DAL","JAX"]},
{r:52,n:"Curtis Samuel",p:"WR",age:29,tm:"BUF",aav:8.0,stats:"658 YDS · 4 TD · 54 REC",tags:["BUF","NE","NYJ"]},
{r:78,n:"Adam Thielen",p:"WR",age:36,tm:"CAR",aav:6.0,stats:"567 YDS · 3 TD · 48 REC",tags:["CAR","RETIRE","MIN"]},
{r:100,n:"Allen Lazard",p:"WR",age:30,tm:"NYJ",aav:5.0,stats:"412 YDS · 3 TD · 36 REC",tags:["NYJ","GB","NE"]},
{r:120,n:"Kendrick Bourne",p:"WR",age:30,tm:"NE",aav:4.5,stats:"503 YDS · 2 TD · 40 REC",tags:["NE","SF","CLE"]},
{r:142,n:"Jakobi Meyers",p:"WR",age:28,tm:"LV",aav:8.0,stats:"710 YDS · 4 TD · 61 REC",tags:["LV","MIA","ATL"]},
// ── Tight Ends ──
{r:10,n:"Mike Gesicki",p:"TE",age:29,tm:"CIN",aav:11.0,stats:"735 YDS · 5 TD · 63 REC",tags:["CIN","JAX","NYG"]},
{r:35,n:"Tyler Conklin",p:"TE",age:29,tm:"NYJ",aav:8.0,stats:"621 YDS · 3 TD · 51 REC",tags:["NYJ","CHI","DEN"]},
{r:65,n:"Jonnu Smith",p:"TE",age:30,tm:"MIA",aav:7.0,stats:"582 YDS · 5 TD · 44 REC",tags:["MIA","MIN","HOU"]},
{r:90,n:"Hayden Hurst",p:"TE",age:31,tm:"LAC",aav:5.0,stats:"432 YDS · 4 TD · 38 REC",tags:["LAC","CLE","BUF"]},
{r:135,n:"Austin Hooper",p:"TE",age:30,tm:"NE",aav:3.5,stats:"295 YDS · 2 TD · 28 REC",tags:["NE","ATL","DEN"]},
// ── Offensive Tackles ──
{r:4,n:"Trent Williams",p:"OT",age:37,tm:"SF",aav:20.0,stats:"96.3 PFF Grade · 3 Sacks Allowed",tags:["SF","RETIRE","NYJ"]},
{r:14,n:"Ronnie Stanley",p:"OT",age:31,tm:"BAL",aav:14.0,stats:"82.1 PFF Grade · 5 Sacks Allowed",tags:["BAL","NYG","TEN"]},
{r:28,n:"D.J. Humphries",p:"OT",age:31,tm:"ARI",aav:12.0,stats:"Missed 2025 · Knee · 78 PFF Career",tags:["ARI","CIN","DEN"]},
{r:48,n:"Mike McGlinchey",p:"OT",age:31,tm:"DEN",aav:10.0,stats:"72.4 PFF Grade · 7 Sacks Allowed",tags:["DEN","IND","NYJ"]},
{r:85,n:"George Fant",p:"OT",age:32,tm:"HOU",aav:5.0,stats:"68.3 PFF Grade · Swing Tackle",tags:["HOU","NE","JAX"]},
// ── Interior Offensive Line ──
{r:16,n:"Robert Hunt",p:"IOL",age:28,tm:"CAR",aav:16.0,stats:"84.7 PFF Grade · Elite Run Blocker",tags:["CAR","DAL","MIA"]},
{r:32,n:"Connor Williams",p:"IOL",age:28,tm:"MIA",aav:10.0,stats:"Returning from ACL · 79 PFF Career",tags:["MIA","NE","SEA"]},
{r:60,n:"Austin Corbett",p:"IOL",age:29,tm:"CAR",aav:7.0,stats:"74.2 PFF Grade · Versatile",tags:["CAR","ATL","MIN"]},
{r:88,n:"Ben Cleveland",p:"IOL",age:28,tm:"BAL",aav:4.0,stats:"69.8 PFF Grade · Guard Depth",tags:["BAL","NE","TEN"]},
{r:118,n:"James Daniels",p:"IOL",age:28,tm:"PIT",aav:6.0,stats:"71.3 PFF Grade · Started 16 Games",tags:["PIT","CHI","CLE"]},
// ── Defensive Line ──
{r:6,n:"Quinnen Williams",p:"DL",age:28,tm:"NYJ",aav:24.0,stats:"10.5 Sacks · 55 Pressures · 64 Tackles",tags:["NYJ","DAL","CHI"]},
{r:18,n:"Dexter Lawrence",p:"DL",age:28,tm:"NYG",aav:22.0,stats:"4.5 Sacks · 41 Pressures · 57 Tackles",tags:["NYG","DEN","TEN"]},
{r:38,n:"Daron Payne",p:"DL",age:28,tm:"WAS",aav:15.0,stats:"5.0 Sacks · 38 Pressures · 62 Tackles",tags:["WAS","HOU","ATL"]},
{r:62,n:"D.J. Jones",p:"DL",age:29,tm:"DEN",aav:8.0,stats:"2.5 Sacks · 22 Pressures · 45 Tackles",tags:["DEN","MIN","CAR"]},
{r:98,n:"Sheldon Rankins",p:"DL",age:30,tm:"HOU",aav:5.0,stats:"3.0 Sacks · 25 Pressures · 38 Tackles",tags:["HOU","NYJ","LV"]},
{r:128,n:"Justin Ellis",p:"DL",age:33,tm:"KC",aav:2.5,stats:"NT · 32 Tackles · Run Stuffer",tags:["KC","NE","BUF"]},
// ── Edge Rushers ──
{r:3,n:"Uchenna Nwosu",p:"EDGE",age:28,tm:"SEA",aav:20.0,stats:"11.5 Sacks · 62 Pressures · 48 Tackles",tags:["SEA","DAL","NYG"]},
{r:9,n:"Josh Sweat",p:"EDGE",age:28,tm:"PHI",aav:16.0,stats:"8.5 Sacks · 51 Pressures · 42 Tackles",tags:["PHI","MIA","HOU"]},
{r:20,n:"Jadeveon Clowney",p:"EDGE",age:33,tm:"CAR",aav:10.0,stats:"6.0 Sacks · 34 Pressures · 36 Tackles",tags:["CAR","DAL","BAL"]},
{r:42,n:"Emmanuel Ogbah",p:"EDGE",age:31,tm:"MIA",aav:8.0,stats:"5.5 Sacks · 30 Pressures · 33 Tackles",tags:["MIA","IND","JAX"]},
{r:68,n:"Yannick Ngakoue",p:"EDGE",age:30,tm:"BAL",aav:7.0,stats:"7.0 Sacks · 38 Pressures · 28 Tackles",tags:["BAL","LV","CHI"]},
{r:92,n:"Carl Lawson",p:"EDGE",age:30,tm:"NYJ",aav:6.0,stats:"4.0 Sacks · 29 Pressures · 31 Tackles",tags:["NYJ","ATL","CLE"]},
{r:112,n:"Dawuane Smoot",p:"EDGE",age:29,tm:"JAX",aav:5.0,stats:"5.5 Sacks · 27 Pressures · 29 Tackles",tags:["JAX","DEN","GB"]},
{r:145,n:"Marcus Davenport",p:"EDGE",age:28,tm:"MIN",aav:4.0,stats:"3.0 Sacks · Health Concerns",tags:["MIN","CAR","NYJ"]},
// ── Linebackers ──
{r:7,n:"Roquan Smith",p:"LB",age:28,tm:"BAL",aav:20.0,stats:"143 Tackles · 4.5 Sacks · 3 INT",tags:["BAL","CHI","DAL"]},
{r:24,n:"Bobby Wagner",p:"LB",age:36,tm:"WAS",aav:11.0,stats:"134 Tackles · 2.5 Sacks · 1 INT",tags:["WAS","SEA","RETIRE"]},
{r:45,n:"Tremaine Edmunds",p:"LB",age:27,tm:"CHI",aav:14.0,stats:"112 Tackles · 2.0 Sacks · 2 INT",tags:["CHI","HOU","NYJ"]},
{r:70,n:"Josey Jewell",p:"LB",age:30,tm:"DEN",aav:6.0,stats:"96 Tackles · 1.5 Sacks · 1 FF",tags:["DEN","TEN","MIN"]},
{r:108,n:"Alex Anzalone",p:"LB",age:30,tm:"DET",aav:5.0,stats:"88 Tackles · 1.0 Sack · 2 PD",tags:["DET","NYG","NE"]},
{r:138,n:"Myles Jack",p:"LB",age:31,tm:"PIT",aav:3.5,stats:"78 Tackles · Veteran Leader",tags:["PIT","RETIRE","JAX"]},
// ── Cornerbacks ──
{r:11,n:"Marshon Lattimore",p:"CB",age:29,tm:"WAS",aav:18.0,stats:"3 INT · 12 PD · 54 Tackles",tags:["WAS","NYG","KC"]},
{r:26,n:"Donte Jackson",p:"CB",age:30,tm:"PIT",aav:12.0,stats:"4 INT · 14 PD · 48 Tackles",tags:["PIT","CAR","NYJ"]},
{r:44,n:"Kristian Fulton",p:"CB",age:27,tm:"LAC",aav:10.0,stats:"2 INT · 11 PD · 52 Tackles",tags:["LAC","TEN","GB"]},
{r:72,n:"Fabian Moreau",p:"CB",age:30,tm:"NYJ",aav:5.0,stats:"1 INT · 8 PD · 45 Tackles",tags:["NYJ","WAS","CHI"]},
{r:102,n:"Rock Ya-Sin",p:"CB",age:28,tm:"MIN",aav:5.5,stats:"2 INT · 9 PD · 42 Tackles",tags:["MIN","IND","NE"]},
{r:122,n:"Amani Oruwariye",p:"CB",age:29,tm:"HOU",aav:3.5,stats:"1 INT · 7 PD · 38 Tackles",tags:["HOU","DET","ATL"]},
{r:148,n:"Bryce Callahan",p:"CB",age:33,tm:"TEN",aav:2.5,stats:"Slot CB · 6 PD · 34 Tackles",tags:["TEN","DEN","RETIRE"]},
// ── Safeties ──
{r:13,n:"Budda Baker",p:"S",age:29,tm:"ARI",aav:14.0,stats:"118 Tackles · 2 INT · 3 FF · 6 PD",tags:["ARI","PHI","KC"]},
{r:34,n:"Quandre Diggs",p:"S",age:32,tm:"SEA",aav:8.0,stats:"85 Tackles · 3 INT · 5 PD",tags:["SEA","DAL","MIN"]},
{r:50,n:"Marcus Epps",p:"S",age:28,tm:"LV",aav:7.0,stats:"78 Tackles · 2 INT · 4 PD",tags:["LV","PHI","DEN"]},
{r:82,n:"Marcus Williams",p:"S",age:28,tm:"BAL",aav:9.0,stats:"62 Tackles · 2 INT · Missed 6 Games",tags:["BAL","HOU","NYJ"]},
{r:115,n:"Jordan Poyer",p:"S",age:33,tm:"MIA",aav:4.0,stats:"68 Tackles · 1 INT · 3 PD",tags:["MIA","BUF","RETIRE"]},
{r:150,n:"Vonn Bell",p:"S",age:30,tm:"CAR",aav:3.5,stats:"72 Tackles · 1 INT · 2 FF",tags:["CAR","CIN","NE"]},
// ── Additional Notable FAs (filling to 150+) ──
{r:17,n:"Mike Evans",p:"WR",age:33,tm:"TB",aav:18.0,stats:"1,004 YDS · 8 TD · 74 REC",tags:["TB","DAL","BAL"]},
{r:19,n:"Calais Campbell",p:"DL",age:39,tm:"MIA",aav:8.0,stats:"5.5 Sacks · 36 Pressures · Iron Man",tags:["MIA","RETIRE","BAL"]},
{r:21,n:"Kirk Cousins",p:"QB",age:38,tm:"ATL",aav:15.0,stats:"Benched · 1,516 YDS · 9 TD · 8 INT",tags:["ATL","CLE","RETIRE"]},
{r:23,n:"Danielle Hunter",p:"EDGE",age:30,tm:"HOU",aav:18.0,stats:"9.0 Sacks · 48 Pressures · 38 Tackles",tags:["HOU","NYG","SEA"]},
{r:27,n:"Tyler Lockett",p:"WR",age:33,tm:"SEA",aav:8.0,stats:"652 YDS · 4 TD · 55 REC",tags:["SEA","RETIRE","DAL"]},
{r:29,n:"Derrick Henry",p:"RB",age:32,tm:"BAL",aav:8.0,stats:"1,407 YDS · 16 TD · 32 REC",tags:["BAL","TEN","RETIRE"]},
{r:31,n:"Patrick Peterson",p:"CB",age:36,tm:"PIT",aav:3.0,stats:"Veteran CB · 2 INT · 7 PD",tags:["RETIRE","PIT","ARI"]},
{r:33,n:"Zack Martin",p:"IOL",age:35,tm:"DAL",aav:8.0,stats:"83.2 PFF Grade · Elite Guard",tags:["RETIRE","DAL","SF"]},
{r:36,n:"Za'Darius Smith",p:"EDGE",age:33,tm:"DET",aav:10.0,stats:"7.5 Sacks · 40 Pressures",tags:["DET","CLE","CAR"]},
{r:37,n:"Grady Jarrett",p:"DL",age:31,tm:"ATL",aav:12.0,stats:"4.0 Sacks · 35 Pressures · 55 Tackles",tags:["ATL","DAL","NYJ"]},
{r:39,n:"Amari Cooper",p:"WR",age:32,tm:"BUF",aav:12.0,stats:"642 YDS · 4 TD · 50 REC",tags:["BUF","DAL","KC"]},
{r:41,n:"Leonard Williams",p:"DL",age:31,tm:"SEA",aav:14.0,stats:"6.0 Sacks · 40 Pressures",tags:["SEA","NYG","CHI"]},
{r:43,n:"Justin Simmons",p:"S",age:31,tm:"ATL",aav:10.0,stats:"92 Tackles · 4 INT · 6 PD",tags:["ATL","KC","DEN"]},
{r:46,n:"Christian Wilkins",p:"DL",age:29,tm:"LV",aav:16.0,stats:"5.0 Sacks · 38 Pressures · 58 Tackles",tags:["LV","MIA","CHI"]},
{r:47,n:"Stephon Gilmore",p:"CB",age:35,tm:"MIN",aav:4.0,stats:"1 INT · 8 PD · Veteran",tags:["MIN","RETIRE","DAL"]},
{r:49,n:"DeAndre Hopkins",p:"WR",age:34,tm:"KC",aav:8.0,stats:"610 YDS · 6 TD · 53 REC",tags:["KC","TEN","RETIRE"]},
{r:51,n:"Hunter Henry",p:"TE",age:31,tm:"NE",aav:9.0,stats:"652 YDS · 4 TD · 55 REC",tags:["NE","DAL","LAC"]},
{r:53,n:"Leonard Floyd",p:"EDGE",age:32,tm:"SF",aav:8.0,stats:"6.0 Sacks · 32 Pressures",tags:["SF","BUF","MIN"]},
{r:54,n:"Khalil Mack",p:"EDGE",age:34,tm:"LAC",aav:8.0,stats:"5.5 Sacks · Veteran Presence",tags:["LAC","CHI","RETIRE"]},
{r:56,n:"Geno Smith",p:"QB",age:35,tm:"SEA",aav:15.0,stats:"3,624 YDS · 22 TD · 10 INT",tags:["SEA","NYG","LV"]},
{r:57,n:"Stefon Diggs",p:"WR",age:33,tm:"HOU",aav:10.0,stats:"Returning from ACL · Elite When Healthy",tags:["HOU","BUF","DAL"]},
{r:59,n:"Dalvin Cook",p:"RB",age:31,tm:"DAL",aav:3.0,stats:"392 YDS · 2 TD · Limited Role",tags:["DAL","MIN","RETIRE"]},
{r:61,n:"Cam Heyward",p:"DL",age:36,tm:"PIT",aav:8.0,stats:"4.0 Sacks · 32 Pressures · Leader",tags:["PIT","RETIRE","CLE"]},
{r:63,n:"Brandin Cooks",p:"WR",age:33,tm:"DAL",aav:5.0,stats:"512 YDS · 3 TD · 42 REC",tags:["DAL","NE","NYJ"]},
{r:64,n:"Shaquille Leonard",p:"LB",age:29,tm:"IND",aav:5.0,stats:"Returning · Former All-Pro",tags:["IND","JAX","PHI"]},
{r:66,n:"Dalton Schultz",p:"TE",age:28,tm:"HOU",aav:8.0,stats:"548 YDS · 4 TD · 48 REC",tags:["HOU","DAL","JAX"]},
{r:67,n:"Tyler Boyd",p:"WR",age:31,tm:"CIN",aav:6.0,stats:"534 YDS · 3 TD · 50 REC",tags:["CIN","TEN","NE"]},
{r:69,n:"Charvarius Ward",p:"CB",age:29,tm:"SF",aav:14.0,stats:"3 INT · 13 PD · 52 Tackles",tags:["SF","NYG","DAL"]},
{r:71,n:"Cam Robinson",p:"OT",age:29,tm:"JAX",aav:12.0,stats:"75.8 PFF Grade · LT Starter",tags:["JAX","NYG","MIN"]},
{r:73,n:"Javon Hargrave",p:"DL",age:31,tm:"SF",aav:11.0,stats:"4.0 Sacks · 30 Pressures",tags:["SF","PHI","CLE"]},
{r:74,n:"Hunter Renfrow",p:"WR",age:29,tm:"LV",aav:5.0,stats:"Slot WR · 428 YDS · 2 TD",tags:["LV","NE","CIN"]},
{r:76,n:"David Montgomery",p:"RB",age:28,tm:"DET",aav:6.0,stats:"892 YDS · 7 TD · 22 REC",tags:["DET","CHI","GB"]},
{r:77,n:"D'Onta Foreman",p:"RB",age:28,tm:"CLE",aav:2.5,stats:"615 YDS · 4 TD · Power Back",tags:["CLE","CAR","HOU"]},
{r:79,n:"Odell Beckham Jr.",p:"WR",age:33,tm:"MIA",aav:4.0,stats:"378 YDS · 2 TD · Limited",tags:["MIA","RETIRE","NYG"]},
{r:80,n:"Taylor Moton",p:"OT",age:30,tm:"CAR",aav:12.0,stats:"78.4 PFF Grade · RT Starter",tags:["CAR","NYJ","CIN"]},
{r:81,n:"Neville Gallimore",p:"DL",age:28,tm:"DAL",aav:5.0,stats:"3.0 Sacks · 20 Pressures",tags:["DAL","ATL","MIN"]},
{r:83,n:"Jaylon Smith",p:"LB",age:30,tm:"NE",aav:3.0,stats:"72 Tackles · Rotational",tags:["NE","DAL","NYG"]},
{r:84,n:"Kyle Fuller",p:"CB",age:33,tm:"DEN",aav:3.0,stats:"1 INT · 6 PD · Veteran",tags:["DEN","CHI","RETIRE"]},
{r:86,n:"Isaiah Oliver",p:"CB",age:28,tm:"ATL",aav:4.5,stats:"2 INT · 8 PD · 45 Tackles",tags:["ATL","SF","GB"]},
{r:87,n:"Akiem Hicks",p:"DL",age:35,tm:"CLE",aav:3.0,stats:"2.0 Sacks · Run Stuffer",tags:["CLE","RETIRE","NE"]},
{r:89,n:"David Njoku",p:"TE",age:29,tm:"CLE",aav:10.0,stats:"748 YDS · 5 TD · 60 REC",tags:["CLE","MIA","DAL"]},
{r:91,n:"Morgan Moses",p:"OT",age:33,tm:"NYJ",aav:6.0,stats:"74.1 PFF Grade · Durable",tags:["NYJ","BAL","IND"]},
{r:93,n:"Terrel Bernard",p:"LB",age:26,tm:"BUF",aav:7.0,stats:"105 Tackles · 2.0 Sacks",tags:["BUF","JAX","MIN"]},
{r:94,n:"Jabrill Peppers",p:"S",age:29,tm:"NE",aav:6.0,stats:"62 Tackles · 1 INT · 2 FF",tags:["NE","CLE","NYG"]},
{r:96,n:"Jamal Adams",p:"S",age:30,tm:"TEN",aav:5.0,stats:"55 Tackles · Box Safety",tags:["TEN","SEA","DAL"]},
{r:97,n:"Austin Ekeler",p:"RB",age:30,tm:"WAS",aav:4.0,stats:"536 YDS · 3 TD · 45 REC",tags:["WAS","NE","LAC"]},
{r:99,n:"Dre Greenlaw",p:"LB",age:28,tm:"SF",aav:7.0,stats:"Returning from Achilles",tags:["SF","DAL","SEA"]},
{r:101,n:"Jessie Bates III",p:"S",age:28,tm:"ATL",aav:14.0,stats:"98 Tackles · 5 INT · 8 PD",tags:["ATL","PHI","CIN"]},
{r:103,n:"Germaine Pratt",p:"LB",age:28,tm:"CIN",aav:6.0,stats:"88 Tackles · 1.5 Sacks",tags:["CIN","TEN","ATL"]},
{r:104,n:"Carlton Davis",p:"CB",age:28,tm:"DET",aav:9.0,stats:"2 INT · 10 PD · 48 Tackles",tags:["DET","TB","HOU"]},
{r:106,n:"Noah Fant",p:"TE",age:27,tm:"SEA",aav:7.0,stats:"502 YDS · 3 TD · 42 REC",tags:["SEA","DEN","IND"]},
{r:107,n:"Pat Elflein",p:"IOL",age:31,tm:"CLE",aav:4.0,stats:"72.1 PFF Grade · Center",tags:["CLE","NE","MIA"]},
{r:109,n:"Arden Key",p:"EDGE",age:28,tm:"JAX",aav:5.5,stats:"4.5 Sacks · 28 Pressures",tags:["JAX","SF","TEN"]},
{r:111,n:"Ahkello Witherspoon",p:"CB",age:29,tm:"PIT",aav:4.0,stats:"1 INT · 7 PD · 38 Tackles",tags:["PIT","LV","SEA"]},
{r:113,n:"Matt Judon",p:"EDGE",age:33,tm:"ATL",aav:7.0,stats:"4.0 Sacks · 28 Pressures",tags:["ATL","NE","HOU"]},
{r:114,n:"Damien Harris",p:"RB",age:28,tm:"BUF",aav:2.0,stats:"312 YDS · 2 TD · Short Yardage",tags:["BUF","NE","JAX"]},
{r:116,n:"La'El Collins",p:"OT",age:32,tm:"CIN",aav:6.0,stats:"71.8 PFF Grade · RT",tags:["CIN","DAL","BUF"]},
{r:117,n:"Foley Fatukasi",p:"DL",age:29,tm:"JAX",aav:5.0,stats:"2.0 Sacks · NT · Run Stuffer",tags:["JAX","NYJ","IND"]},
{r:119,n:"Eli Apple",p:"CB",age:29,tm:"DAL",aav:2.5,stats:"0 INT · 5 PD · 40 Tackles",tags:["DAL","NYG","CIN"]},
{r:121,n:"Darren Waller",p:"TE",age:33,tm:"NYG",aav:5.0,stats:"Limited · Health Questions",tags:["NYG","RETIRE","LV"]},
{r:123,n:"Kwon Alexander",p:"LB",age:30,tm:"NYJ",aav:3.0,stats:"65 Tackles · Rotational",tags:["NYJ","SF","DEN"]},
{r:124,n:"Jason Kelce",p:"IOL",age:38,tm:"PHI",aav:0,stats:"RETIRED · Analyst",tags:["RETIRED"]},
{r:126,n:"Jourdan Lewis",p:"CB",age:29,tm:"DAL",aav:4.0,stats:"2 INT · 8 PD · Slot CB",tags:["DAL","NYJ","CLE"]},
{r:127,n:"Tyler Higbee",p:"TE",age:32,tm:"LAR",aav:4.0,stats:"Returning from ACL · 402 YDS",tags:["LAR","DET","DAL"]},
{r:129,n:"Jonathan Allen",p:"DL",age:30,tm:"WAS",aav:14.0,stats:"5.0 Sacks · Torn Pec · Recovery",tags:["WAS","DAL","NYG"]},
{r:131,n:"Sam Hubbard",p:"EDGE",age:29,tm:"CIN",aav:8.0,stats:"5.5 Sacks · 30 Pressures",tags:["CIN","NE","TEN"]},
{r:132,n:"Adoree' Jackson",p:"CB",age:30,tm:"NYG",aav:5.0,stats:"1 INT · 9 PD · 42 Tackles",tags:["NYG","TEN","DEN"]},
{r:133,n:"Mike Hughes",p:"CB",age:27,tm:"MIN",aav:3.0,stats:"1 INT · 6 PD · Depth",tags:["MIN","ATL","DET"]},
{r:134,n:"Tre'Quan Smith",p:"WR",age:29,tm:"NO",aav:3.0,stats:"356 YDS · 2 TD",tags:["NO","ATL","DEN"]},
{r:136,n:"Evan Engram",p:"TE",age:30,tm:"JAX",aav:8.0,stats:"682 YDS · 4 TD · 58 REC",tags:["JAX","NYG","CIN"]},
{r:137,n:"Trey Smith",p:"IOL",age:26,tm:"KC",aav:14.0,stats:"87.2 PFF Grade · Top Guard",tags:["KC","DAL","NYG"]},
{r:139,n:"DJ Chark",p:"WR",age:29,tm:"LAC",aav:4.0,stats:"412 YDS · 3 TD",tags:["LAC","JAX","DET"]},
{r:141,n:"Jamison Crowder",p:"WR",age:32,tm:"WAS",aav:2.0,stats:"Slot WR · 286 YDS",tags:["WAS","NYJ","RETIRE"]},
{r:143,n:"Blake Martinez",p:"LB",age:31,tm:"LV",aav:3.0,stats:"78 Tackles · Steady",tags:["LV","GB","NYG"]},
{r:144,n:"Cody Ford",p:"IOL",age:28,tm:"NYJ",aav:3.0,stats:"68.4 PFF Grade · Swing OL",tags:["NYJ","BUF","ARI"]},
{r:146,n:"Keanu Neal",p:"S",age:30,tm:"TB",aav:3.0,stats:"58 Tackles · 1 FF · Hybrid",tags:["TB","ATL","DAL"]},
{r:147,n:"Tre Herndon",p:"CB",age:28,tm:"JAX",aav:2.0,stats:"0 INT · 5 PD · Depth",tags:["JAX","IND","HOU"]},
{r:149,n:"Tyler Biadasz",p:"IOL",age:28,tm:"WAS",aav:6.0,stats:"76.3 PFF Grade · Center",tags:["WAS","DAL","NE"]},
{r:151,n:"Marquise Brown",p:"WR",age:29,tm:"ARI",aav:7.0,stats:"Returning from Injury · Speed",tags:["ARI","KC","BAL"]},
{r:152,n:"Jimmy Garoppolo",p:"QB",age:34,tm:"LAR",aav:5.0,stats:"Backup · 812 YDS · 4 TD",tags:["LAR","LV","RETIRE"]},
{r:153,n:"Tevin Coleman",p:"RB",age:33,tm:"IND",aav:1.5,stats:"215 YDS · 1 TD · Depth",tags:["IND","RETIRE","ATL"]},
{r:154,n:"Chris Boswell",p:"K",age:34,tm:"PIT",aav:5.0,stats:"32/35 FG · 94.3% · All-Pro",tags:["PIT","NYJ","DAL"]},
{r:156,n:"Tommy Townsend",p:"P",age:29,tm:"KC",aav:3.0,stats:"47.2 AVG · 25 Inside 20",tags:["KC","LAC","HOU"]},
{r:157,n:"Jason Myers",p:"K",age:34,tm:"SEA",aav:3.5,stats:"28/32 FG · 87.5%",tags:["SEA","MIN","DEN"]},
{r:158,n:"Mitch Wishnowsky",p:"P",age:32,tm:"SF",aav:2.5,stats:"46.8 AVG · 22 Inside 20",tags:["SF","JAX","CLE"]},
{r:159,n:"Graham Gano",p:"K",age:38,tm:"NYG",aav:2.0,stats:"22/26 FG · Injury Prone",tags:["NYG","RETIRE","DAL"]},
{r:160,n:"Jake Bailey",p:"P",age:27,tm:"MIA",aav:2.0,stats:"45.9 AVG · 20 Inside 20",tags:["MIA","NE","TEN"]},
];

export default FREE_AGENTS;
